version: "3.8"

services:
  app:
    environment:
      - DB_HOST=
    image: steamx/react-dapp
    container_name: react-dapp
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HOMEDIR: ${HOMEDIR}
        PORT: ${PORT}
        NODE_ENV: "development"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:${HOMEDIR}/src:rw
      - ./:${HOMEDIR}/
      - frontend_node_modules:${HOMEDIR}/node_modules

volumes:
  frontend_node_modules: